### ISSUE TITLE
Cyclic reboots as long as no device credentials are available

### ISSUE THREAD

**Issue by hms-dow** [hms-networks/flexy-cumulocity-connector#14]
During tests on customer site, the assignment of device credentials failed due to issues with connecting to the on-premise Cumulocity.

Before the device credentials were assigned to the device, the Flexy rebooted every 5 to 8 minutes.
Event log shows "Java Critical Error: 15" followed by "Systemstart, FWR: 14.5s1" and "Grund für Neustart: Skriptanforderung" (=Reason for restart: requested by script):
![grafik](https://user-images.githubusercontent.com/80829302/174731220-8aed2707-c4b4-4369-88ee-0c194ac03896.png)
The FTP connection was not needed to trigger the error.

System is using German language

RT-Log:
![grafik](https://user-images.githubusercontent.com/80829302/174730797-fadafb35-2ff1-4b65-9a1f-2f9ae733a475.png)

Internet connection is established using mobile data connection.

**Comment by hms-dow** [comment]
@alexjhawk: Is it correct, that this issue was not addressed in the latest [Release 1.4.0](https://github.com/hms-networks/flexy-cumulocity-connector/releases/tag/v1.4.0) or should this be solved by Bug Fix "Fixed a bug which could cause the application to trigger a restart when initialization or startup is paused or delayed" in [Release 1.3.4](https://github.com/hms-networks/flexy-cumulocity-connector/releases/tag/v1.3.4)?

**Comment by alexjhawk** [comment]
@hms-dow, I believe several fixes have resolved this in the past year. While this issue was not directly addressed, there were several changes to help prevent this from occurring.

Namely, commit 7f31d655 from 4/27/2023 (Update watchdog setup location) addressed a potential case where the connector startup procedure could cause unexpected reboots under multiple scenarios, including pending device credentials.

Additionally, around the same time, support was added for device credential configuration via API, making the connector pause to wait to provision device credentials if they are not configured. 
- This change should also help prevent the issue, as the connector will no longer try to connect to device provisioning until it has the credentials.

Outside of the connector, the newly released Ewon firmware v14.8s0 contains a fix that should prevent unexpected MQTT client behavior when messages are sent without a connection. This may not affect the mentioned issue, but it is worth noting as it occurs under similar circumstances.
- [https://hmsnetworks.blob.core.windows.net/www/docs/librariesprovider10/downloads-monitored/manuals/release-notes/firmware-releases-cosy131-flexy.txt?sfvrsn=8f341cd7_67](https://hmsnetworks.blob.core.windows.net/www/docs/librariesprovider10/downloads-monitored/manuals/release-notes/firmware-releases-cosy131-flexy.txt?sfvrsn=8f341cd7_67)
