### ISSUE TITLE
Cumulocity device keeps waiting for connection and errors in Flexy realtime logs

### ISSUE THREAD

**Issue by DriesDebouver** [hms-networks/flexy-cumulocity-connector#19]
Dear,

I followed the [QUICK-START.md](https://github.com/hms-networks/flexy-cumulocity-connector/blob/main/QUICK-START.md) and everything went smooth but the registered device in Cumulocity keeps saying "Waiting for connection".

In the HMS Ewon Flexy the Java program started correctly but shows some error logs in the Realtime logs.
First there was: _"JVM - An error occurred while reading data from the historical log."_
After that: _"MQTT - Disconnected (unexpected)"_
And then: _"The MQTT manager is not available to send historical data. Skipping data poll!"_

I don't know why the MQTT manager is unavailable or why there is none.
In the Java program source code I found that this message get's logged when _mqttMgr == null_.

However, there are constantly _MQTT CONNECT_ and _MQTT CONNACK_ messages transfered so there must be some sort of connection.

Anybody knows what the problem is or could be?

Thanks in advance.

Best regards,
Dries

![Cumulocity device waiting for connection blurred](https://user-images.githubusercontent.com/28297720/188115678-32b851e3-d125-4fe8-8be8-c8417f08dd25.jpg)

![Realtime logs blurred](https://user-images.githubusercontent.com/28297720/188114847-0ecdbdfe-9885-4b38-babf-55955a334313.jpg)

![Realtime logs 2 blurred](https://user-images.githubusercontent.com/28297720/188115400-1634f4ed-7872-4978-aa3c-2b20c5c7df4c.jpg)

**Comment by alexjhawk** [comment]
Hi @DriesDebouver,

This sounds like the device is trying to connect with a known username/password instead of reaching out for registration. This can happen if the `DeviceUsername`, `DevicePassword`, and/or `DeviceTenant` fields in the configuration file are not set to `<automatically filled>`. This value indicates that the device needs to enter registration mode and retrieve new credentials from Cumulocity.

Are you able to verify that the `DeviceUsername`, `DevicePassword`, and `DeviceTenant` fields in your configuration file match the proper values? I've attached the example from the quick start guide below.

![image](https://user-images.githubusercontent.com/51409174/188681772-3f2b1135-b508-4cf9-84f4-7fe5be6e3532.png)

Best regards,

@alexjhawk

**Comment by DriesDebouver** [comment]
Hi @alexjhawk,

That is correct.
I have set these fields to `<automatically filled>` and changed the Bootstrap fields aswell and this works.
Thanks.

**Comment by alexjhawk** [comment]
Hi @DriesDebouver,

I am glad to hear that you were able to resolve the issue and get things working again.

I will now close this issue -- if you have any further issues, please feel free to reopen this issue, or create a new, relevant issue.

Best regards,

@alexjhawk
