### ISSUE TITLE
Certificate & private Instance

### ISSUE THREAD

**Issue by elvinsp** [hms-networks/flexy-cumulocity-connector#31]
Hello,

I have trouble connecting the Agent to Cumulocity. I'm working with an private Instance of Cumulocity and therefore I think I might have a problem with the certificate. Is this assumption correct? Can I specify an crt that is on the Ewon Flexy?

Best Regards

**Comment by TomKimsey** [comment]
@elvinsp Due to the holiday in the United States our Cumulocity connector developer is out of the office and will return on November 28th.

In the meantime if you have the latest version of the connector [Version 1.3.1](https://github.com/hms-networks/flexy-cumulocity-connector/releases/tag/v1.3.1) you can specify a certificate URL for your Cumulocity instance. https://github.com/hms-networks/flexy-cumulocity-connector#certificate-url-certificateurl

[https://github.com/hms-networks/flexy-cumulocity-connector#certificate-url-certificateurl](https://github.com/hms-networks/flexy-cumulocity-connector#certificate-url-certificateurl)

**Comment by alexjhawk** [comment]
Hi @elvinsp,

Thank you for reaching out. 

Currently, the connector is only tested against the Cumulocity cloud. Tom is correct, though. In the new version, 1.3.0, and later, the URL for the certificate can be modified using the configuration file. 
- To use a private instance of Cumulocity, you'll need to modify the configuration file "Certificate URL" field with a download URL for your Cumulocity certificate (public key, never private key).

The table of contents for the README.md file was missing the proper entry for the "Certificate URL" field, but I have since updated it on the live GitHub webpage. This fix will also be in the updated PDF documentation during the next patch/release.
- In the meantime, please refer to the README.md page on the GitHub repository home page, https://github.com/hms-networks/flexy-cumulocity-connector, or you can still use the direct link Tom specified above, https://github.com/hms-networks/flexy-cumulocity-connector#certificate-url-certificateurl.

Please let me know if you're still having issues.

Best regards,

@alexjhawk

**Comment by janhumble** [comment]
We are trying to connect the Flexy with the latest instructions and certificate path to a public Cumulocity tenant.  We are getting null pointers on mqtt ssl handshake.  Running firmware 14.5s on a Flexy 205.
![image](https://user-images.githubusercontent.com/19224631/221690746-a5149707-7928-4838-91c5-d62b672d2b8a.png)
Has this been verified with Cumulocity recently?

**Comment by alexjhawk** [comment]
Hi @janhumble,

Thank you for reporting the issue you are encountering. I have created a standalone GitHub issue to track comments and progress relevant to your report.

You can follow along and get more information here: https://github.com/hms-networks/flexy-cumulocity-connector/issues/35
