### ISSUE TITLE
NPE thrown during retrieval of MQTT status in device provisioning client.

### ISSUE THREAD

**Issue by alexjhawk** [hms-networks/flexy-cumulocity-connector#35]
**Original Report By: @janhumble
Original Report Permalink: https://github.com/hms-networks/flexy-cumulocity-connector/issues/31#issuecomment-1447129264
Original Report Content:**

We are trying to connect the Flexy with the latest instructions and certificate path to a public Cumulocity tenant.  We are getting null pointers on mqtt ssl handshake.  Running firmware 14.5s on a Flexy 205.
![image](https://user-images.githubusercontent.com/19224631/221690746-a5149707-7928-4838-91c5-d62b672d2b8a.png)
Has this been verified with Cumulocity recently?

**Comment by janhumble** [comment]
Thank you Alex for looking into this.  We are trying to troubleshoot a remote device for a customer.  We are also seeing some errors in the modem and DNS.  It's using the Ewon modem.
![EVENT LOGS](https://user-images.githubusercontent.com/19224631/222212100-9b554273-ed99-4169-8003-aa1ecf22e9d8.PNG)

**Comment by alexjhawk** [comment]
The likely culprit is the DNS issue you are seeing in the event log: `dns-No response from server (certs.godaddy.com)`

If the system cannot resolve the DNS for certs.godaddy.com, it cannot download the required CA certificate to connect to Cumulocity. This is indicated also by the entry in the event log `mqtt-Problem configuring SSL/TLS` which tells us the certificate is either incorrect or corrupt/missing.

**Comment by it-hms** [comment]
This exception is caught and the software continues to run, but the stacktrace is printed because of the log level being 6. I realize that this can cause some confusion. 

There some cellular settings that should be changed from the defaults. Please check _Max outgoing call duration_ in  system->Communication->Internet Connection-> Modem->Outgoing->Global  
This value should be 0 indicating no limit for outgoing calls. Here, the MQTT connection is regarded as a "call" to the cellular modem. 

![image](https://user-images.githubusercontent.com/72526279/224068687-1ae71ebd-4c5b-4de5-8726-e38bdaae9ec4.png)
