### ISSUE TITLE
List of c8y_SupportedOperations fragment

### ISSUE THREAD

**Issue by it-hms** [hms-networks/flexy-cumulocity-connector#53]
Please provide a list of all current device status information sent to the c8y_SupportedOperations fragment in Cumulocity, as well as potential new fields like WAN IP, Mobile SIM ICCID, Signal Strength, Location, etc
https://cumulocity.com/guides/10.15.0/reference/device-management-library/
I'm looking for additional information to be sent by the Ewon Flexy to improve remote access and troubleshooting,

**Comment by alexjhawk** [comment]
Hi @it-hms,

Are you discussing adding a list of current c8y_SupportedOperations within the documentation?

It is worth investigating new fields that could be included, like the mentioned WAN IP, Mobile SIM ICCID, etc. However, implementation should be split into a separate issue because some of these values would require more consistent updating. The connector currently only sends values when connecting to MQTT upon startup.
